### ISSUE TITLE
models are not available

### ISSUE THREAD

**Issue by esgnn** [chanyn/3Dpose_ssl#1]
Hi there,

Models are not available.

Thanks

**Comment by chanyn** [comment]
Models are available now.

**Comment by yselivonchyk** [comment]
> Models are available now.

Hi,

I think models are still not there.

Even if so, you guys did an amazing job making your work available for an average 1080 owner!

**Comment by kezewang** [comment]
Thanks a lot for your kind attention to our work!

Please use the following link to access:
https://drive.google.com/file/d/1DS50Na6fbTaG-mHVzFbINx9AE5Wgpqa6/view

**Comment by chanyn** [comment]
You can download final extension models in https://drive.google.com/open?id=1dMuPuD_JdHuMIMapwE2DwgJ2IGK04xhQ. We mention it in "Model Inference" of README.
And you can find other model download address in "Training" of README.
