### ISSUE TITLE
test_human16.sh error

### ISSUE THREAD

**Issue by mingsjtu** [chanyn/3Dpose_ssl#10]
When I modified the test_human16.sh
[EE369_evaluation.log](https://github.com/chanyn/3Dpose_ssl/files/2974833/EE369_evaluation.log)
 and the template_16_merge.prototxt , and run sh test_human16.sh ,I received an error like this

I0317 13:23:44.770185 20271 net.cpp:411] evalution -> evalution
*** Aborted at 1552800224 (unix time) try "date -d @1552800224" if you are using GNU date ***
PC: @     0x7f95b27acfec caffe::MPJPEEvaluationLayer<>::LayerSetUp()
*** SIGSEGV (@0x0) received by PID 20271 (TID 0x7f95b326b780) from PID 0; stack trace: ***
    @     0x7f95b080b4b0 (unknown)
    @     0x7f95b27acfec caffe::MPJPEEvaluationLayer<>::LayerSetUp()
    @     0x7f95b28ebe4f caffe::Net<>::Init()
    @     0x7f95b28ee130 caffe::Net<>::Net()
    @           0x409897 test()
    @           0x4078f4 main
    @     0x7f95b07f6830 __libc_start_main
    @           0x408209 _start
    @                0x0 (unknown)
Segmentation fault (core dumped)

And I need your help ,please.

**Comment by kezewang** [comment]
Which version of Ubuntu are you using now?  This seems to be an internal error of your linux system.
