### ISSUE TITLE
Build caffe follow that?

### ISSUE THREAD

**Issue by NguyenDangBinh** [chanyn/3Dpose_ssl#11]

**Comment by NguyenDangBinh** [comment]
dear,
Can I build caffe like that?
https://gist.github.com/FrancoisPl/e7375c3a08c1b73d5547709e97405253

**Comment by kezewang** [comment]
I am not sure. Please refer to http://caffe.berkeleyvision.org/install_apt.html for more details.

**Comment by NguyenDangBinh** [comment]
dear @kezewang ,
Can you please build caffe step by step? and post more detail?
Thank you so much.

**Comment by kezewang** [comment]
Ideally, you can just type "make -j8 && make pycaffe" to build caffe after 
"sudo apt-get install libprotobuf-dev libleveldb-dev libsnappy-dev libopencv-dev libhdf5-serial-dev protobuf-compiler
sudo apt-get install --no-install-recommends libboost-all-dev
sudo apt-get install libgflags-dev libgoogle-glog-dev liblmdb-dev"
If you meet with any errors, please copy them to me. I can fix them.

**Comment by NguyenDangBinh** [comment]
dear @kezewang,
some errors alway happen. Can you help me?

**Comment by NguyenDangBinh** [comment]
dear @kezewang,
In this repo, can you show how to install Matlab, caffe,..?

**Comment by NguyenDangBinh** [comment]
dear,
the error when make all
CXX src/caffe/solver.cpp
In file included from ./include/caffe/util/device_alternate.hpp:40:0,
                 from ./include/caffe/common.hpp:19,
                 from ./include/caffe/blob.hpp:8,
                 from ./include/caffe/net.hpp:10,
                 from ./include/caffe/solver.hpp:7,
                 from src/caffe/solver.cpp:6:
./include/caffe/util/cudnn.hpp: In function ‘const char* cudnnGetErrorString(cudnnStatus_t)’:
./include/caffe/util/cudnn.hpp:21:10: warning: enumeration value ‘CUDNN_STATUS_RUNTIME_PREREQUISITE_MISSING’ not handled in switch [-Wswitch]
   switch (status) {
          ^
./include/caffe/util/cudnn.hpp: In function ‘void caffe::cudnn::setConvolutionDesc(cudnnConvolutionStruct**, cudnnTensorDescriptor_t, cudnnFilterDescriptor_t, int, int, int, int)’:
./include/caffe/util/cudnn.hpp:113:70: error: too few arguments to function ‘cudnnStatus_t cudnnSetConvolution2dDescriptor(cudnnConvolutionDescriptor_t, int, int, int, int, int, int, cudnnConvolutionMode_t, cudnnDataType_t)’
       pad_h, pad_w, stride_h, stride_w, 1, 1, CUDNN_CROSS_CORRELATION));
                                                                      ^
./include/caffe/util/cudnn.hpp:15:28: note: in definition of macro ‘CUDNN_CHECK’
     cudnnStatus_t status = condition; \
                            ^
In file included from ./include/caffe/util/cudnn.hpp:5:0,
                 from ./include/caffe/util/device_alternate.hpp:40,
                 from ./include/caffe/common.hpp:19,
                 from ./include/caffe/blob.hpp:8,
                 from ./include/caffe/net.hpp:10,
                 from ./include/caffe/solver.hpp:7,
                 from src/caffe/solver.cpp:6:
/home/binh/anaconda2/envs/OpenSSL/include/cudnn.h:500:27: note: declared here
 cudnnStatus_t CUDNNWINAPI cudnnSetConvolution2dDescriptor( cudnnConvolutionDescriptor_t convDesc,
                           ^
Makefile:575: recipe for target '.build_release/src/caffe/solver.o' failed
make: *** [.build_release/src/caffe/solver.o] Error 1

**Comment by chanyn** [comment]
Maybe your CUDNN was installed unsuccessfully, installation of MATLAB can follow https://blog.csdn.net/qq_32892383/article/details/79670871 or GOOGLE.

**Comment by NguyenDangBinh** [comment]
dear,
Cudnn is installed successfully.
