### ISSUE TITLE
why does this happened

### ISSUE THREAD

**Issue by wzzz-zh** [chanyn/3Dpose_ssl#13]
an error occured when i run the train.sh in examples/2D_to_3D/:

F0321 11:37:40.849474  8301 insert_splits.cpp:29] Unknown bottom blob 'clip' (layer 'lstm1', bottom index 1)
*** Check failure stack trace: ***
    @     0x7f1f11f135cd  google::LogMessage::Fail()
    @     0x7f1f11f15433  google::LogMessage::SendToLog()
    @     0x7f1f11f1315b  google::LogMessage::Flush()
    @     0x7f1f11f15e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f1f1259725c  caffe::InsertSplits()
    @     0x7f1f125c0d3e  caffe::Net<>::Init()
    @     0x7f1f125c41f1  caffe::Net<>::Net()
    @     0x7f1f1279905a  caffe::Solver<>::InitTrainNet()
    @     0x7f1f127995c7  caffe::Solver<>::Init()
    @     0x7f1f1279995a  caffe::Solver<>::Solver()
    @     0x7f1f125cfcd3  caffe::Creator_AdamSolver<>()
    @           0x40b018  train()
    @           0x4078d4  main
    @     0x7f1f106a9830  __libc_start_main
    @           0x4081e9  _start
    @              (nil)  (unknown)
Aborted (core dumped)

this is the lstm part in bilstm.prototxt:(i have change nothing of this .prototxt besides assign "..../data/h36m" to "root_folder" )

lstm1 layer
layer {
  name: "lstm1"
  type: "LSTM"
  bottom: "fc-reshape"
  bottom: "clip"
  top: "lstm1"
  recurrent_param {
    num_output: 1024
    weight_filler {
      type: "uniform"
      min: -0.01
      max: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}

i have never use caffe ever before, someone can solve this?
thanks so much!

**Comment by kezewang** [comment]
Dear dfefefef,

Please comment the line 57, 58 and 59 in the file named ''bilstm.prototxt''.

Best regards,
keze
