### ISSUE TITLE
mask3d error

### ISSUE THREAD

**Issue by chaytonmin** [chanyn/3Dpose_ssl#18]
![屏幕快照 2019-04-08 上午9 55 50](https://user-images.githubusercontent.com/40260488/55694061-d277e880-59e4-11e9-9d04-9db63f256eee.png)
the prob equals 0.02 in the codes ,  but the error is that prob needs to be an integer?

**Comment by kezewang** [comment]
Sorry about that! We have fixed this issue by updating the caffe proto.
