### ISSUE TITLE
tensorflow implementation

### ISSUE THREAD

**Issue by esgnn** [chanyn/3Dpose_ssl#2]
Hi,

Would you mind sharing how to implement in tensorflow in more detail?

Thanks

**Comment by chanyn** [comment]
We have updated README.md to include more details.

**Comment by NguyenDangBinh** [comment]
dear,
The same question about that.

**Comment by NguyenDangBinh** [comment]
dear,
Would you mind sharing how to implement in tensorflow such as Window or Ubuntu, Python 2 or Python 3, .... from installing the beginning.
The same question for Matlab, C++.
THANK YOU.

**Comment by chanyn** [comment]
Hello, we just implement part of the whole model in Tensorflow using Python2. Others of this model are implemented by Caffe using C++. If you have an interest in this project, we expect you to transfer whole model into Tensorflow or MXNET.

**Comment by NguyenDangBinh** [comment]
dear @chanyn ,
Did You implement Project in Ubuntu or Window? I want to rebuild them.

**Comment by chanyn** [comment]
This project is implemented in Ubuntu.

**Comment by Abhilash-Chandran** [comment]
Dear Chanyn,

I am interested in porting this into TensorFlow. My initial question in this regard is how do I identify without digging much into the code, which parts are already implemented in tensorflow and which is in Caffe. Please bear my ignorance, as I don't have any experience with Caffe. Especially which folders in the caffe should I look into carefully.

**Comment by NguyenDangBinh** [comment]
dear @chanyn,
I have plan to change into tensorflow but I currently have not experience to build caffe. I have the problem to install.

**Comment by NguyenDangBinh** [comment]
dear @chanyn,
I still have issues in make caffe.
Can you help me?
(OpenSSL) binh@binh:~/3Dpose_ssl/caffe-3dssl$ make all
CXX src/caffe/solver.cpp
In file included from ./include/caffe/util/device_alternate.hpp:40:0,
                 from ./include/caffe/common.hpp:19,
                 from ./include/caffe/blob.hpp:8,
                 from ./include/caffe/net.hpp:10,
                 from ./include/caffe/solver.hpp:7,
                 from src/caffe/solver.cpp:6:
./include/caffe/util/cudnn.hpp: In function ‘const char* cudnnGetErrorString(cudnnStatus_t)’:
./include/caffe/util/cudnn.hpp:21:10: warning: enumeration value ‘CUDNN_STATUS_RUNTIME_PREREQUISITE_MISSING’ not handled in switch [-Wswitch]
   switch (status) {
          ^
./include/caffe/util/cudnn.hpp: In function ‘void caffe::cudnn::setConvolutionDesc(cudnnConvolutionStruct**, cudnnTensorDescriptor_t, cudnnFilterDescriptor_t, int, int, int, int)’:
./include/caffe/util/cudnn.hpp:113:70: error: too few arguments to function ‘cudnnStatus_t cudnnSetConvolution2dDescriptor(cudnnConvolutionDescriptor_t, int, int, int, int, int, int, cudnnConvolutionMode_t, cudnnDataType_t)’
       pad_h, pad_w, stride_h, stride_w, 1, 1, CUDNN_CROSS_CORRELATION));
                                                                      ^
./include/caffe/util/cudnn.hpp:15:28: note: in definition of macro ‘CUDNN_CHECK’
     cudnnStatus_t status = condition; \
                            ^
In file included from ./include/caffe/util/cudnn.hpp:5:0,
                 from ./include/caffe/util/device_alternate.hpp:40,
                 from ./include/caffe/common.hpp:19,
                 from ./include/caffe/blob.hpp:8,
                 from ./include/caffe/net.hpp:10,
                 from ./include/caffe/solver.hpp:7,
                 from src/caffe/solver.cpp:6:
/home/binh/anaconda2/envs/OpenSSL/include/cudnn.h:500:27: note: declared here
 cudnnStatus_t CUDNNWINAPI cudnnSetConvolution2dDescriptor( cudnnConvolutionDescriptor_t convDesc,
                           ^
Makefile:575: recipe for target '.build_release/src/caffe/solver.o' failed
make: *** [.build_release/src/caffe/solver.o] Error 1

**Comment by NguyenDangBinh** [comment]
dear @chanyn,
I still have issues in make caffe.
Can you help me?
(OpenSSL) binh@binh:~/3Dpose_ssl/caffe-3dssl$ make all
CXX src/caffe/solver.cpp
In file included from ./include/caffe/util/device_alternate.hpp:40:0,
                 from ./include/caffe/common.hpp:19,
                 from ./include/caffe/blob.hpp:8,
                 from ./include/caffe/net.hpp:10,
                 from ./include/caffe/solver.hpp:7,
                 from src/caffe/solver.cpp:6:
./include/caffe/util/cudnn.hpp: In function ‘const char* cudnnGetErrorString(cudnnStatus_t)’:
./include/caffe/util/cudnn.hpp:21:10: warning: enumeration value ‘CUDNN_STATUS_RUNTIME_PREREQUISITE_MISSING’ not handled in switch [-Wswitch]
   switch (status) {
          ^
./include/caffe/util/cudnn.hpp: In function ‘void caffe::cudnn::setConvolutionDesc(cudnnConvolutionStruct**, cudnnTensorDescriptor_t, cudnnFilterDescriptor_t, int, int, int, int)’:
./include/caffe/util/cudnn.hpp:113:70: error: too few arguments to function ‘cudnnStatus_t cudnnSetConvolution2dDescriptor(cudnnConvolutionDescriptor_t, int, int, int, int, int, int, cudnnConvolutionMode_t, cudnnDataType_t)’
       pad_h, pad_w, stride_h, stride_w, 1, 1, CUDNN_CROSS_CORRELATION));
                                                                      ^
./include/caffe/util/cudnn.hpp:15:28: note: in definition of macro ‘CUDNN_CHECK’
     cudnnStatus_t status = condition; \
                            ^
In file included from ./include/caffe/util/cudnn.hpp:5:0,
                 from ./include/caffe/util/device_alternate.hpp:40,
                 from ./include/caffe/common.hpp:19,
                 from ./include/caffe/blob.hpp:8,
                 from ./include/caffe/net.hpp:10,
                 from ./include/caffe/solver.hpp:7,
                 from src/caffe/solver.cpp:6:
/home/binh/anaconda2/envs/OpenSSL/include/cudnn.h:500:27: note: declared here
 cudnnStatus_t CUDNNWINAPI cudnnSetConvolution2dDescriptor( cudnnConvolutionDescriptor_t convDesc,
                           ^
Makefile:575: recipe for target '.build_release/src/caffe/solver.o' failed
make: *** [.build_release/src/caffe/solver.o] Error 1

**Comment by kezewang** [comment]
Please try cudnn 5.1 instead.

**Comment by NguyenDangBinh** [comment]
dear @kezewang,
Can you give me a moment though temviewer?

**Comment by NguyenDangBinh** [comment]
dear @kezewang ,
can you help me?

**Comment by kezewang** [comment]
Dear @NguyenDangBinh,
do you address your issue?
