### ISSUE TITLE
linux_square_imgs

### ISSUE THREAD

**Issue by akhalili** [chanyn/3Dpose_ssl#20]
Can we have the dataset in GoogleDrive?

**Comment by flurrux** [comment]
i second that. anything but baidu.

**Comment by akhalili** [comment]
I have problem to untar the concatenated .tar.gz0[0,1,2,3,4] files. Any success?

**Comment by flurrux** [comment]
I can't even get the download to start on my machine, sorry

**Comment by kezewang** [comment]
We are sorry for this. We have shared the dataset on the dropbox at 
https://www.dropbox.com/s/x53axj3r6s90auz/ramdisk_h36m.zip?dl=0

**Comment by akhalili** [comment]
Thanks @kezewang . I am counting the seconds for the upload to finish. Thanks for sharing with us.

**Comment by kezewang** [comment]
The old link is failed with the server error. Please try the following one:
https://www.dropbox.com/s/bxlk3v2lgd2cqo8/ramdisk_h36m.zip?dl=0

**Comment by akhalili** [comment]
Has completely been extracted. Thanks for unblocking me. It's time to explore the package.
We may update the link in the master branch
Thanks
