### ISSUE TITLE
How to project the 3D points onto the 2D square images?

### ISSUE THREAD

**Issue by huge123** [chanyn/3Dpose_ssl#21]
Thanks for sharing this wonderful jobs.
The camera parameters provided by Human3.6M are for original images, but how you project the 3D points onto the cropped square images?  It seems that the some parameters, at least the center of image, in intrinsic matirx have changed.

Looking forward to your reply, thanks.

**Comment by kezewang** [comment]
Dear huge123, 
Thanks a lot for your kind attention to our work. Please refer to the following address for more details about data preprocessing.
https://github.com/MudeLin/RPSM/tree/master/util/preprocess
