### ISSUE TITLE
Link expired

### ISSUE THREAD

**Issue by alainux** [chanyn/3Dpose_ssl#23]
Hello, the direct download link containing all datasets and trained models is expired:  https://www.dropbox.com/s/szfkir7hgrc9kfw/3Dpose_ssl.tar.gz?dl=0 , could you please create a new one?

Thank you.

**Comment by kezewang** [comment]
Sorry for that! Please try the following link:
https://www.dropbox.com/s/qycpjinof2ishw9/3Dpose_ssl.tar.gz?dl=0

**Comment by alainux** [comment]
Thank you!

**Comment by cross-zero** [comment]
Hello, the direct download link containing all datasets and trained models is expired again:
https://www.dropbox.com/s/qycpjinof2ishw9/3Dpose_ssl.tar.gz?dl=0 , could you please renew it or maybe create a new one on Google Drive ? Thank you in advance.
