### ISSUE TITLE
Python 3.6 on Window10

### ISSUE THREAD

**Issue by NguyenDangBinh** [chanyn/3Dpose_ssl#5]
dear @chanyn ,
Is this project run with python 3.6 on Window 10?

**Comment by chanyn** [comment]
This project is simple to change to python 3.6. You only need to modify some of the syntaxes. For Windows, i never run any project on this. Maybe you can try.

**Comment by NguyenDangBinh** [comment]
dear @chanyn ,
the first I need to test successfully. After that, I can modify to python 3.

**Comment by NguyenDangBinh** [comment]
dear @chanyn ,
can you show me the tutorials of installing caffe on anaconda on ubuntu 16.04?
I try many times but failing.

**Comment by chanyn** [comment]
I use Caffe in Ubuntu 14.04, but i think installation is similar with Ubuntu16.04. Caffe depends your system environments and other software version. Maybe you should  check your CUDA version, CUDNN  and so on.

**Comment by NguyenDangBinh** [comment]
dear @chanyn ,
I have problems in installing Caffe on Anaconda on Ubuntu 16.04.

**Comment by kezewang** [comment]
Could you provide the error message?

**Comment by NguyenDangBinh** [comment]
dear @chanyn ,
I just installed successfully.
