### ISSUE TITLE
an error occured when I run test_human16.sh

### ISSUE THREAD

**Issue by mingsjtu** [chanyn/3Dpose_ssl#6]
F0311 14:05:49.627907 23105 mpjpe_evalution_layer.cpp:26] Check failed: this->max_min_value_.size() >= 2 (0 vs. 2) 
*** Check failure stack trace: ***
    @     0x7f6e4d4c85cd  google::LogMessage::Fail()
    @     0x7f6e4d4ca433  google::LogMessage::SendToLog()
    @     0x7f6e4d4c815b  google::LogMessage::Flush()
    @     0x7f6e4d4cae1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f6e4dc15230  caffe::MPJPEEvaluationLayer<>::LayerSetUp()
    @     0x7f6e4dd53f4f  caffe::Net<>::Init()
    @     0x7f6e4dd56230  caffe::Net<>::Net()
    @           0x409897  test()
    @           0x4078f4  main
    @     0x7f6e4bc5e830  __libc_start_main
    @           0x408209  _start
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by mingsjtu** [comment]
Can you give me a more clear structure of your dataset "h36m", which is contained in the https://pan.baidu.com/s/1ieLHH9w8tnKPcB836Jxtcw#list/path=%2F. Because the baiduyun down loader is too slow to download such big file , I want you to give me a structure of this link's file .

**Comment by kezewang** [comment]
Please download from the following link:
https://drive.google.com/open?id=11EjXzZQq7yXIBNIw5sDaCO9v9zzs8xbD
