### ISSUE TITLE
Step: Train 2D-to-3D pose 

### ISSUE THREAD

**Issue by NguyenDangBinh** [chanyn/3Dpose_ssl#8]
dear @chanyn,
I run that step and i had error:
(testcaffe) binh@binh:~/3Dpose_ssl-master/caffe-3dssl$ sh examples/2D_to_3D/train.sh
examples/2D_to_3D/train.sh: 7: examples/2D_to_3D/train.sh: ../../build/tools/caffe: not found
can you help me?

**Comment by NguyenDangBinh** [comment]
dear @mingsjtu,

can you help me to train the first step?

**Comment by kezewang** [comment]
Please compile the caffe-3dssl as follows:
cd caffe-3dssl;
vi Makefile.config 
make -j8 && make pycaffe

**Comment by NguyenDangBinh** [comment]
dear @kezewang,
I did not have any experiences about building caffe.
The first, I will install anaconda on Ubuntu 16.04. completed.
The second, what is the steps to build caffe? can you help me?

**Comment by kezewang** [comment]
Please install the dependencies:
sudo apt-get install libprotobuf-dev libleveldb-dev libsnappy-dev libopencv-dev libhdf5-serial-dev protobuf-compiler
sudo apt-get install --no-install-recommends libboost-all-dev
sudo apt-get install libgflags-dev libgoogle-glog-dev liblmdb-dev

Then, you can modify the Makefile.config by updating the relevant path. 
Finally, you can input:
make -j8 && make pycaffe

**Comment by NguyenDangBinh** [comment]
dear @kezewang ,
can you please access to my computer to help me install caffe? (by teamview or ...)
Thank you so much.

**Comment by kezewang** [comment]
Please send your teamviewer id and password to my email: kezewang@gmail.com

**Comment by NguyenDangBinh** [comment]
dear Keze,

Id 1 220 708 968

pass j57pn8

**Comment by NguyenDangBinh** [comment]
dear,
the current password is     a246qv
I am waiting you.

**Comment by kezewang** [comment]
Please give the password of the ubuntu user.

**Comment by NguyenDangBinh** [comment]
dear Keze,
pass Ubuntu user is  123
