### ISSUE TITLE
What is mean?

### ISSUE THREAD

**Issue by NguyenDangBinh** [chanyn/3Dpose_ssl#9]
dear,
" After set up Human3.6m dataset following its illustration and download above training/testing list. You should update “root_folder” paths in CAFFE_ROOT/examples/.../*.prototxt for images and annotation director. "
That mean I should replace " root_folder: "Human3.6m_ROOT_DIR" " in bilstm.prototxt? and how to replace?

**Comment by kezewang** [comment]
For example, one can replace it like this:
  image_data_lstm_param {
    source: "/home/keze/Codes/3Dpose_ssl/data/h36m/16skel_train_2d3d_clip.txt"
    root_folder: "/home/keze/Codes/3Dpose_ssl/data/h36m/"
    new_height: 368
    new_width: 368
    is_color: true
    batch_size: 5
    shuffle: false
    label_dim: 81
    is_shuffle_batch: true
  }
